### ISSUE TITLE
Gulp plugin should support multiple files to be compiled separately

### ISSUE THREAD

**Issue by nazar-pc** [google/closure-compiler-js#17]
``` javascript
const gulp     = require('gulp');
const compiler = require('google-closure-compiler-js').gulp();

gulp.task('dist', function () {
    return gulp.src([
    'js/file1.js',
    'js/file2.js'
    ])
        .pipe(compiler())
        .pipe(gulp.dest('dist')); // I want `file1.min.js` and `file2.min.js` here,
                                  // but getting `compiled.js`
});
```

**Comment by samthor** [comment]
This is tricky, but we match the existing Gulp plugins for Closure. If your two files are totally separate targets with no other relationships, I'd encourage you to write multiple tasks. Otherwise, Closure wants to merge them together to optimize your code.

Having said that, [Closure has an advanced syntax to generate different files for different modules](http://stackoverflow.com/questions/10395810/how-do-i-split-my-javascript-into-modules-using-googles-closure-compiler/10401030#10401030). We don't currently support that. Is that what you want?

**Comment by nazar-pc** [comment]
Looks like it might be what I need. Even though I do not quite understand how it might integrate with Gulp.

UglifyJS allows to minify files separately, why Closure compiler wouldn't'? I see it like following:
```javascript
...
    .pipe(compiler({
        multi        : true,
        jsOutputFile : function (filename) {
            return prefix(filename);
        }
    })
...
```
It doesn't have to do something with Closure compiler, it might be implemented purely as Gulp plugin functionality.

**Comment by Dylan-Chapman** [comment]
+1

The current behavior is really odd for a Gulp plugin.

**Comment by ChadKillingsworth** [comment]
Code splitting is supported in the main distribution. Please switch to Please switch to the main distribution at https://github.com/google/closure-compiler-npm
