### ISSUE TITLE
Investigate Webpack integration

### ISSUE THREAD

**Issue by appsforartists** [google/closure-compiler-js#2]
It looks like there's a Webpack plugin that passes options to the CC jar:

https://www.npmjs.com/package/webpack-closure-compiler

We should try replacing it's lib/runner with this package and see if it works.  If so, maybe open a PR on that package.

**Comment by samthor** [comment]
Instead of modifying an existing tool, I've [written a plugin in this repo](https://github.com/google/closure-compiler-js/blob/master/lib/webpack.js). It works mod a few pending tasks-

* it doesn't clone/flatten the options (aka '--foo_bar' => 'fooBar')
* we don't yet dive into the original files via source maps to show users where their errors really occured

**Comment by concavelenz** [comment]
The compiler does support "input" source maps to show the original location
for error messages, it just needs to be wired up.

**Comment by samthor** [comment]
Webpack support is here. The input source map issue is different and is part of the real compiler.
