### ISSUE TITLE
Different results than Java?

### ISSUE THREAD

**Issue by appsforartists** [google/closure-compiler-js#9]
I was just spying on a new minifier called babeli.  They have a chart where they compare the performance of the Java and JS versions of closure against themselves:

https://github.com/babel/babili#benchmarks

Closure is the most successful minifier and the JS build of Closure is the least.

Here's the code that generates the benchmarks: https://github.com/babel/babili/blob/e38a050ab396df8f7cbcdb6d2784cc7c6193d803/scripts/benchmark.js#L89-L101

Is it a fair test?  Should the Java and JS versions be producing different output?

**Comment by Dominator008** [comment]
For Closure Compiler Java, looks like they are using an old version built at least 10 months ago. For Closure Compiler JS, I believe they are using 20160713.0.3, which was released last month.

It's not 100% fair, because Closure does some checking and runs on not just the source file but also a bunch of externs. I've created https://github.com/babel/babili/pull/101 to update both the Java and the JS version to 20160822.0.0, turn off most of the checks and include only the language externs.

My results:
Backbone.js
                   raw     raw win gzip   gzip win parse time run
uglify        21.79kB 221%    7.29kB 169%     2ms        242ms
closure     21.67kB 223%    7.37kB 167%     2ms        1311ms
babili        21.62kB 223%    7.4kB  165%     1ms        724ms
closure js 24.01kB 191%    8.04kB 144%     2ms        3607ms

React.js
                raw      raw win gzip    gzip win parse time run
closure    171.46kB 265%    52.97kB 168%     11ms       2246ms
uglify       176.36kB 255%    53.13kB 167%     11ms       1208ms
closure js 174.08kB 260%    53.58kB 165%     15ms       11967ms
babili        177.28kB 253%    55.18kB 157%     14ms       3171ms

jQuery.js
                  raw      raw win gzip    gzip win parse time run
uglify        94.27kB  218%    32.78kB 158%     9ms        990ms
closure     94.23kB  218%    33.38kB 153%     8ms        1973ms
closure js 95.63kB  213%    33.83kB 150%     8ms        10738ms
babili       101.52kB 195%    35kB    141%     7ms        4302ms

Closure Java and Closure JS should generate different output. I think there's some optimization that is not run under Closure JS. We will investigate further.

**Comment by samthor** [comment]
(I presume you mean _shouldn't_.)

It's not really fair for this test but those numbers are only with simple optimizations (not fair because I don't think it'd compile at all with advanced).

**Comment by appsforartists** [comment]
My assumption would be since this is the same algorithm being run on a different VM, the output should be identical across {java,javascript}, so long as the same configuration is used.  Glad you guys are looking into this.

**Comment by MatrixFrog** [comment]
This is probably better for the mailing list than as an "issue"

**Comment by NekR** [comment]
@MatrixFrog, well, then post please a link to mailing list thread here, because some people may to track this issue. e.g. to start using this on production.

**Comment by concavelenz** [comment]
Enabling TracerMode.TIMING_ONLY and comparing the two traces should tell
you which pass are run and whether we are unintentionally skipping one.

**Comment by appsforartists** [comment]
@MatrixFrog, I'm interested to hear the motivation for that decision.  An Issue seems like a way easier way to keep track of a potential issue than a mailing list thread.  It's discoverable (both by team members and external authors) and explicitly "open" or "closed."

I hate mailing list discussions.  Invariably, they either invite every even-mildly-opinionated person to chime in on a centithread or die when people run out of off-the-cuff remarks to make (often, the same thread can suffer both).  In contrast, Issues are never forgotten - even dormant ones come back to the fore when someone has something new to contribute.

**Comment by concavelenz** [comment]
I think it is fair that this stay open here.

**Comment by ChadKillingsworth** [comment]
If this is still an issue, it can be posted at Please switch to the main distribution at https://github.com/google/closure-compiler
